ALTER FUNCTION fVolumeCompras (@MES VARCHAR)
RETURNS TABLE AS 
RETURN (
	SELECT
		C.CPF,
		C.NOME,
		C.VOLUME_DE_COMPRA,
		SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
		CASE WHEN SUM(INF.QUANTIDADE) > C.VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS' ELSE 'VENDAS VÁLIDAS' END AS RESULTADO
	FROM TABELA_DE_CLIENTES C
	INNER JOIN NOTAS_FISCAIS NF
	ON C.CPF = NF.CPF
	INNER JOIN ITENS_NOTAS_FISCAIS INF
	ON NF.NUMERO = INF.NUMERO
	WHERE CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) = @MES
	GROUP BY C.CPF, C.NOME, C.VOLUME_DE_COMPRA
)

SELECT * FROM fVolumeCompras('2015-01')