DROP FUNCTION IF EXISTS SumByYear;

CREATE FUNCTION SumByYear(@Ano INT)
RETURNS FLOAT AS
BEGIN
RETURN (
	SELECT SUM(VENDA_ANO) FROM
	
	(SELECT
		P.SABOR,
		SUM(I.QUANTIDADE) AS VENDA_ANO
	FROM TABELA_DE_PRODUTOS P
	INNER JOIN ITENS_NOTAS_FISCAIS I
	ON P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
	INNER JOIN NOTAS_FISCAIS NF
	ON I.NUMERO = NF.NUMERO
	WHERE YEAR(NF.DATA_VENDA) = @Ano
	GROUP BY P.SABOR) 
	AS VENDAS_SABOR
	)
END


SELECT
		P.SABOR,
		SUM(I.QUANTIDADE) AS VENDA_ANO,
		CONVERT(DEC(10,2), SUM(I.QUANTIDADE) / dbo.SumByYear(2015) * 100) AS PORCENTUAL
	FROM TABELA_DE_PRODUTOS P
	INNER JOIN ITENS_NOTAS_FISCAIS I
	ON P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
	INNER JOIN NOTAS_FISCAIS NF
	ON I.NUMERO = NF.NUMERO
	WHERE YEAR(NF.DATA_VENDA) = 2015
	GROUP BY P.SABOR
	ORDER BY SUM(I.QUANTIDADE) DESC
