CREATE TRIGGER [Excluir pessoa]
ON Pessoa
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @IDP VARCHAR(50)

	SELECT @IDP = IDPessoa FROM DELETED

	DELETE FROM EventoPessoa WHERE IDPessoa = @IDP
	
	DELETE FROM Pessoa WHERE IDPessoa = @IDP
END