CREATE TRIGGER [Excluir País]
ON PAÍS
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @País VARCHAR(35)
	SELECT @País = País FROM DELETED
	DELETE FROM CIDADE WHERE País = @País
	DELETE FROM RIO WHERE País = @País
	DELETE FROM RIO WHERE Nascente = @País
	DELETE FROM PAÍS WHERE País = @País
END

DELETE FROM PAÍS WHERE País = 'USA'

SELECT * FROM PAÍS
SELECT * FROM CIDADE
SELECT * FROM RIO